name: Workspace Resource Exist
on: 
  repository_dispatch:
    types: [workspace_exist_test]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repository
        id: checkout_repository
        uses: actions/checkout@master
      
      - name: workspaceCreationTest
        id: workspaceCreationTest
        uses: ${{ github.event.client_payload.test_branch }}
        with:
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
          parameters_file: "workspace_resource_exists.json"