name: Workspace Resource Create
on: 
  repository_dispatch:
    types: [workspace_create_test]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repository
        id: checkout_repository
        uses: actions/checkout@master
      
      - name: workspaceCreationTest
        id: workspaceCreationTest
        uses: ashishonce/aml-workspace@master
        with:
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
          parameters_file: "workspace_resource_creation.json"
